### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by sudo-nano** [wrightcameron/mekansimRatioCalculator#2] opened 2024-05-22 06:50 UTC
Attempting to clone the repo and build with `cargo build` fails. 

Build errors: 
```
error[E0053]: method `summarize` has an incompatible type for trait
  --> src/setups.rs:69:24
   |
69 |     fn summarize(&self){
   |                        ^ expected `std::string::String`, found `()`
   |
note: type in trait
  --> src/setups.rs:8:28
   |
8  |     fn summarize(&self) -> String;
   |                            ^^^^^^
   = note: expected signature `fn(&TrinarySetup) -> std::string::String`
              found signature `fn(&TrinarySetup)`
help: change the output type to match the trait
   |
69 |     fn summarize(&self) -> std::string::String{
   |                         ++++++++++++++++++++++

error[E0599]: no method named `summarize` found for struct `Boiler` in the current scope
  --> src/setups.rs:71:21
   |
71 |         self.boiler.summarize();
   |                     ^^^^^^^^^ method not found in `Boiler`
   |
  ::: src/boiler.rs:2:1
   |
2  | pub struct Boiler {
   | ----------------- method `summarize` not found for this struct
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `Setup` defines an item `summarize`, perhaps you need to implement it
  --> src/setups.rs:6:1
   |
6  | pub trait Setup {
   | ^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0053, E0599.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `mekanism_ratio_calculator` (bin "mekanism_ratio_calculator") due to 2 previous errors
```

**Comment by wrightcameron** [comment] 2024-05-23 16:45
Thank you for creating an Issue.  Let me try to reproduce the issue and see what the problem is.  

As stated in the readme the code is very much a work in progress, and the nature of this and the complexity of the calculations has run away from me that its been a month since i've had time to look at this repo.  In its current state though being able to calculate Turbines and Reactors should be able to work, so I'll look into this issue.

The future progress I hope to make is figure out how to incorporate sodium reactors, though this does require better calculations for power which might be based on mincraft ticks and something the code can't emulate at the moment.

When I do get that point I would be using this video as reference.  https://www.youtube.com/watch?v=yQzm5Ou5Bps

**Comment by wrightcameron** [comment] 2024-05-23 16:50
Honestly probably the bug got created, cause I was to focused on running `cargo test` all the time.

**Comment by wrightcameron** [comment] 2024-05-24 16:35
Must have broken master but the fix or change was on the dev branch, so I just merged it and pushed it up.  The recent changes that must have broken the tool were my slow change to have turbines and reactors be part of a set of two or three so I could eventually get sodium setups working.  The problem is I fell down a rabbit hole of unable to verify reactors from optimal turbine then calc reactor from that turbine, and then calculate turbine based on that reactor.  It should loop but the formulas have a bias of blocks preferred that can't be overcome unless a variable like power is added which would then require the addition of minecraft ticks to be calculated.

Either way here is the prompt showing it works, I have it working for binary setups and for you to either start with a turbine or reactor, only water for now.  There are dead areas that haven't been added yet but its a work in progress.

```bash
mekanismRatioCalc/target/debug$ ./mekanism_ratio_calculator 
Welcome to Mekanism Ratio Calculator, interactive mode.
Command (m: for help):
m
Options:
c: create setup
l: List created setups
p: print created setups
r: Get all materials needed for select setup
q: Quit
c
Create. Options:
m: multi - multi block setup.
m
Create new Mutliblock group setup:
b: binary - Two multiblocks attached together
t: trinary - Three multiblock attached setup
q: quit - Return to top menu
b
Create turbine first (y/n)
y
Turbines Options:
o: optimal - optimal based on dimension.
f: flow - optimal based on max flow of water
m: manual - get calculations based on already existing turbine.
o
Input turbine length & depth.
15
Input turbine height.
15
A 15x15x15 Turbine
- Shaft 8, Blades 16, and Coils 4
- Vents: 429
- Dispersers: 168
- Condensers: 215
- Max Flow Rate 13728000 mB/t, Max Water Output 13760000 mB /t
- Capacity 115200000 mJ, Max Energy Production 78445720 mJ

Create an optimal fission reactor for this turbine? (y/n)
y
Succesfully created the binary multi block setup.
m
Options:
c: create setup
l: List created setups
p: print created setups
r: Get all materials needed for select setup
q: Quit
p
A 13x14x14 Fission Reactor
- Fuel Assemblies 686, and Control Rods 66
- Water Burn Rate 13720000 mb/t
- Fuel Surface Area 3326 (m2), Boil Efficiency 1
- Max Burn Rate 686 mB/t
- Heat Capacity 964000 J/K
A 15x15x15 Turbine
- Shaft 8, Blades 16, and Coils 4
- Vents: 429
- Dispersers: 168
- Condensers: 215
- Max Flow Rate 13728000 mB/t, Max Water Output 13760000 mB /t
- Capacity 115200000 mJ, Max Energy Production 78445720 mJ
```

**Closed as completed by wrightcameron** 2024-05-24 16:35 UTC
Labels: bug

**Comment by sudo-nano** [comment] 2024-06-10 04:06
Awesome, thanks!
